# Generated by Django 4.1.7 on 2023-03-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_group_groupdiscussion_remove_result_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadmin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main.student'),
        ),
    ]
