# Generated by Django 4.1.7 on 2023-04-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lecturer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='group_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion', to='main.groupdiscussion'),
        ),
    ]
