# Generated by Django 4.1.7 on 2023-04-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_progress_group_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='group_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.groupdiscussion'),
        ),
    ]
